apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-cont
  lables:
    name: rc-cont
    type: frontend
spec:
  templete:
    metadata:
      name: nginx
      labels:
        name: nginx
    spec:
      container:
        - name: test
          image: nginx
replicas: 5



