apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rd
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: nginx
      labels:
        name: nginx
    spec:
      containers:
        - name: test
          image: nginx
          ports:
            - containerPort: 80
  replicas: 3